const fs = require('fs-extra');
const path = require('path');

const createModules = (dirDst, modules) => {
    const indexPath = path.join(dirDst, 'src/modules/index.js');
    console.log(`Write ${indexPath}`);

    // Ensure the directory exists
    fs.ensureDirSync(path.dirname(indexPath));

    const fileContent = `\
// NOTICE: This file is auto-generated by wl-engine.
${modules.map(module => `import ${module} from './${module}';`).join('\n')}

export default [${modules.join(', ')}];
`;

    fs.writeFileSync(indexPath, fileContent);

    console.log('Write successful!');
};

module.exports = createModules;
